# Generated by Django 5.1.1 on 2024-12-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('otro', 'Otro')], max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('mensaje', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='comentarios_adjuntos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
