# Generated by Django 5.1.1 on 2024-12-06 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('donacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ong', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='donacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.donacion'),
        ),
    ]
