# Generated by Django 5.1.1 on 2024-11-21 19:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0011_rename_logo_tienda_logo_tienda_comuna_tienda_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tienda',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
