# Generated by Django 5.1.1 on 2024-11-17 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0022_alter_subasta_estado_alter_transaccion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subasta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
