# Generated by Django 5.1.1 on 2024-11-21 19:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0024_remove_subasta_created_at_remove_subasta_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subasta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subasta',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
