# Generated by Django 5.1.1 on 2024-11-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0025_subasta_created_at_subasta_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subasta',
            name='updated_at',
        ),
    ]
