# Generated by Django 5.1.1 on 2024-11-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0026_remove_subasta_created_at_remove_subasta_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
