# Generated by Django 5.1.1 on 2024-12-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0027_transaccion_comision_transaccion_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='envio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
