# Generated by Django 5.1.1 on 2024-12-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0029_subasta_precio_subasta_alter_subasta_precio_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subasta',
            name='precio_subasta',
        ),
        migrations.AlterField(
            model_name='subasta',
            name='precio_final',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto',
            field=models.IntegerField(),
        ),
    ]
